//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkRoom.Core.Resources {
    using System;
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LinkRoom.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "LinkRoom".
        /// </summary>
        public static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "⚙ 设置".
        /// </summary>
        public static string MainSettings {
            get {
                return ResourceManager.GetString("MainSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "👥 房间".
        /// </summary>
        public static string MainRooms {
            get {
                return ResourceManager.GetString("MainRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "📋 日志".
        /// </summary>
        public static string MainLog {
            get {
                return ResourceManager.GetString("MainLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "🔄 更新".
        /// </summary>
        public static string MainUpdate {
            get {
                return ResourceManager.GetString("MainUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "P2P 游戏联机 · 单文件便携".
        /// </summary>
        public static string MainTagline {
            get {
                return ResourceManager.GetString("MainTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "🏠 房主模式（创建房间并主持游戏）".
        /// </summary>
        public static string MainHostMode {
            get {
                return ResourceManager.GetString("MainHostMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "房间号 / 联机码".
        /// </summary>
        public static string MainRoomLabel {
            get {
                return ResourceManager.GetString("MainRoomLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "支持 linkroom:// 链接或 房间号:密码".
        /// </summary>
        public static string MainRoomToolTip {
            get {
                return ResourceManager.GetString("MainRoomToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "密码（可选）".
        /// </summary>
        public static string MainPasswordLabel {
            get {
                return ResourceManager.GetString("MainPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "创建房间".
        /// </summary>
        public static string MainCreateButton {
            get {
                return ResourceManager.GetString("MainCreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "加入房间".
        /// </summary>
        public static string MainConnectButton {
            get {
                return ResourceManager.GetString("MainConnectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "断开连接".
        /// </summary>
        public static string MainDisconnectButton {
            get {
                return ResourceManager.GetString("MainDisconnectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "✅ 房间已创建".
        /// </summary>
        public static string MainRoomCreated {
            get {
                return ResourceManager.GetString("MainRoomCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "双击复制房间号".
        /// </summary>
        public static string MainCopyRoomIdTip {
            get {
                return ResourceManager.GetString("MainCopyRoomIdTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "双击复制联机链接".
        /// </summary>
        public static string MainCopyLinkTip {
            get {
                return ResourceManager.GetString("MainCopyLinkTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "复制联机链接".
        /// </summary>
        public static string MainCopyLinkButton {
            get {
                return ResourceManager.GetString("MainCopyLinkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "NAT: ".
        /// </summary>
        public static string MainNatPrefix {
            get {
                return ResourceManager.GetString("MainNatPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to " | 公网: ".
        /// </summary>
        public static string MainPublicSuffix {
            get {
                return ResourceManager.GetString("MainPublicSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "虚拟 IPv4: ".
        /// </summary>
        public static string MainVipPrefix {
            get {
                return ResourceManager.GetString("MainVipPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to " | IPv6: ".
        /// </summary>
        public static string MainIpv6Suffix {
            get {
                return ResourceManager.GetString("MainIpv6Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "复制虚拟 IP".
        /// </summary>
        public static string MainCopyVipButton {
            get {
                return ResourceManager.GetString("MainCopyVipButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "连接测速".
        /// </summary>
        public static string MainSpeedTestButton {
            get {
                return ResourceManager.GetString("MainSpeedTestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "🎮 检测游戏".
        /// </summary>
        public static string MainDetectGameButton {
            get {
                return ResourceManager.GetString("MainDetectGameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "点击设置该游戏端口并一键开房".
        /// </summary>
        public static string MainGameTip {
            get {
                return ResourceManager.GetString("MainGameTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "💬 房间聊天".
        /// </summary>
        public static string MainChatHeader {
            get {
                return ResourceManager.GetString("MainChatHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "发送".
        /// </summary>
        public static string MainSendButton {
            get {
                return ResourceManager.GetString("MainSendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "点击检查更新".
        /// </summary>
        public static string MainCheckUpdateTip {
            get {
                return ResourceManager.GetString("MainCheckUpdateTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "设置".
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "⚙ 高级设置".
        /// </summary>
        public static string SettingsHeader {
            get {
                return ResourceManager.GetString("SettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "连接模式".
        /// </summary>
        public static string SettingsConnectionMode {
            get {
                return ResourceManager.GetString("SettingsConnectionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "LAN 模式（虚拟网卡 + UDP 广播，MC 等自动发现）".
        /// </summary>
        public static string SettingsLanMode {
            get {
                return ResourceManager.GetString("SettingsLanMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "禁用 UPnP 端口映射（对称型 NAT 可关闭此项并启用 UPnP）".
        /// </summary>
        public static string SettingsDisableUpnp {
            get {
                return ResourceManager.GetString("SettingsDisableUpnp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "LAN 模式需管理员权限；轻量模式无需虚拟网卡".
        /// </summary>
        public static string SettingsLanModeHint {
            get {
                return ResourceManager.GetString("SettingsLanModeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "监听端口".
        /// </summary>
        public static string SettingsListenerPort {
            get {
                return ResourceManager.GetString("SettingsListenerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "共享节点（中继）".
        /// </summary>
        public static string SettingsSharedNode {
            get {
                return ResourceManager.GetString("SettingsSharedNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "启用共享节点".
        /// </summary>
        public static string SettingsEnableSharedNode {
            get {
                return ResourceManager.GetString("SettingsEnableSharedNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "默认 public.easytier.top:11010".
        /// </summary>
        public static string SettingsSharedNodeTip {
            get {
                return ResourceManager.GetString("SettingsSharedNodeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "🔒 安全模式".
        /// </summary>
        public static string SettingsSecureMode {
            get {
                return ResourceManager.GetString("SettingsSecureMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "启用安全模式（端到端加密，同网络节点需一致开启）".
        /// </summary>
        public static string SettingsEnableSecureMode {
            get {
                return ResourceManager.GetString("SettingsEnableSecureMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "共享节点的 X25519 公钥（base64），来自节点运营方".
        /// </summary>
        public static string SettingsSecureKeyTip {
            get {
                return ResourceManager.GetString("SettingsSecureKeyTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "共享节点公钥（可选）· 留空 = 仅加密、不验证共享节点身份；填写后锁定公钥，连接错误节点将被拒绝".
        /// </summary>
        public static string SettingsSecureKeyHint {
            get {
                return ResourceManager.GetString("SettingsSecureKeyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "STUN 服务器".
        /// </summary>
        public static string SettingsStunServers {
            get {
                return ResourceManager.GetString("SettingsStunServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "host:port 逗号分隔，留空用默认".
        /// </summary>
        public static string SettingsStunTip {
            get {
                return ResourceManager.GetString("SettingsStunTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "🔄 更新远程 STUN 列表".
        /// </summary>
        public static string SettingsRefreshStun {
            get {
                return ResourceManager.GetString("SettingsRefreshStun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "🔄 刷新网络检测缓存".
        /// </summary>
        public static string SettingsRefreshNetwork {
            get {
                return ResourceManager.GetString("SettingsRefreshNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "自动重连".
        /// </summary>
        public static string SettingsAutoReconnect {
            get {
                return ResourceManager.GetString("SettingsAutoReconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "虚拟 IP / MTU / IPv6".
        /// </summary>
        public static string SettingsVipMtuIpv6 {
            get {
                return ResourceManager.GetString("SettingsVipMtuIpv6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "留空 DHCP".
        /// </summary>
        public static string SettingsVipTip {
            get {
                return ResourceManager.GetString("SettingsVipTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "优先 IPv6".
        /// </summary>
        public static string SettingsPreferIpv6 {
            get {
                return ResourceManager.GetString("SettingsPreferIpv6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "仅 IPv6 模式".
        /// </summary>
        public static string SettingsIpv6Only {
            get {
                return ResourceManager.GetString("SettingsIpv6Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "启用 SOCKS5 代理".
        /// </summary>
        public static string SettingsEnableSocks5 {
            get {
                return ResourceManager.GetString("SettingsEnableSocks5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "SOCKS5 端口".
        /// </summary>
        public static string SettingsSocks5Tip {
            get {
                return ResourceManager.GetString("SettingsSocks5Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "锁定房间（仅房主可加入新成员）".
        /// </summary>
        public static string SettingsRoomLocked {
            get {
                return ResourceManager.GetString("SettingsRoomLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "更新".
        /// </summary>
        public static string SettingsUpdate {
            get {
                return ResourceManager.GetString("SettingsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "启动时自动检查 GitHub 更新".
        /// </summary>
        public static string SettingsAutoCheckUpdate {
            get {
                return ResourceManager.GetString("SettingsAutoCheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "🔄 立即检查更新".
        /// </summary>
        public static string SettingsCheckUpdateNow {
            get {
                return ResourceManager.GetString("SettingsCheckUpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "配置管理".
        /// </summary>
        public static string SettingsConfigManagement {
            get {
                return ResourceManager.GetString("SettingsConfigManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "📤 导出配置".
        /// </summary>
        public static string SettingsExportConfig {
            get {
                return ResourceManager.GetString("SettingsExportConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "📥 导入配置".
        /// </summary>
        public static string SettingsImportConfig {
            get {
                return ResourceManager.GetString("SettingsImportConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "数据存储".
        /// </summary>
        public static string SettingsDataStorage {
            get {
                return ResourceManager.GetString("SettingsDataStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "便携模式（LinkRoomData/ 在 exe 同目录）".
        /// </summary>
        public static string SettingsPortableMode {
            get {
                return ResourceManager.GetString("SettingsPortableMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "开机自启".
        /// </summary>
        public static string SettingsAutoStart {
            get {
                return ResourceManager.GetString("SettingsAutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "暗色模式".
        /// </summary>
        public static string SettingsDarkMode {
            get {
                return ResourceManager.GetString("SettingsDarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "语言".
        /// </summary>
        public static string SettingsLanguage {
            get {
                return ResourceManager.GetString("SettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "切换语言后需重启生效".
        /// </summary>
        public static string SettingsLanguageTip {
            get {
                return ResourceManager.GetString("SettingsLanguageTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "跟随系统".
        /// </summary>
        public static string LangSystem {
            get {
                return ResourceManager.GetString("LangSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "中文".
        /// </summary>
        public static string LangZh {
            get {
                return ResourceManager.GetString("LangZh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "English".
        /// </summary>
        public static string LangEn {
            get {
                return ResourceManager.GetString("LangEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "🎮 游戏端口".
        /// </summary>
        public static string SettingsGamePorts {
            get {
                return ResourceManager.GetString("SettingsGamePorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "🔍 扫描本地游戏端口".
        /// </summary>
        public static string SettingsScanGamePorts {
            get {
                return ResourceManager.GetString("SettingsScanGamePorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "🧪 NAT 检测".
        /// </summary>
        public static string SettingsNatTest {
            get {
                return ResourceManager.GetString("SettingsNatTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "🔍 立即检测 NAT".
        /// </summary>
        public static string SettingsTestNat {
            get {
                return ResourceManager.GetString("SettingsTestNat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "🔍 自检".
        /// </summary>
        public static string SettingsSelfCheck {
            get {
                return ResourceManager.GetString("SettingsSelfCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "📦 导出诊断包".
        /// </summary>
        public static string SettingsExportDiag {
            get {
                return ResourceManager.GetString("SettingsExportDiag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "🌐 Web 面板".
        /// </summary>
        public static string SettingsWebPanel {
            get {
                return ResourceManager.GetString("SettingsWebPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "🎮 扫描 MC Mod".
        /// </summary>
        public static string SettingsScanMods {
            get {
                return ResourceManager.GetString("SettingsScanMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "📦 EasyTier 版本".
        /// </summary>
        public static string SettingsEtVersion {
            get {
                return ResourceManager.GetString("SettingsEtVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "🧩 已加载插件".
        /// </summary>
        public static string SettingsPlugins {
            get {
                return ResourceManager.GetString("SettingsPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "关闭".
        /// </summary>
        public static string SettingsClose {
            get {
                return ResourceManager.GetString("SettingsClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "欢迎使用 LinkRoom".
        /// </summary>
        public static string WizardTitle {
            get {
                return ResourceManager.GetString("WizardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "步骤 1/3 — 选择模式".
        /// </summary>
        public static string WizardStep1Title {
            get {
                return ResourceManager.GetString("WizardStep1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "选择适合你的联机模式".
        /// </summary>
        public static string WizardStep1Desc {
            get {
                return ResourceManager.GetString("WizardStep1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "LAN 模式（MC 等自动发现，需管理员）".
        /// </summary>
        public static string WizardLanMode {
            get {
                return ResourceManager.GetString("WizardLanMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "启动时自动检查更新".
        /// </summary>
        public static string WizardAutoUpdate {
            get {
                return ResourceManager.GetString("WizardAutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "便携模式（数据存 exe 同目录）".
        /// </summary>
        public static string WizardPortable {
            get {
                return ResourceManager.GetString("WizardPortable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "跳过".
        /// </summary>
        public static string WizardSkip {
            get {
                return ResourceManager.GetString("WizardSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "下一步".
        /// </summary>
        public static string WizardNext {
            get {
                return ResourceManager.GetString("WizardNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "房间成员".
        /// </summary>
        public static string PeerTitle {
            get {
                return ResourceManager.GetString("PeerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "👥 房间成员".
        /// </summary>
        public static string PeerHeader {
            get {
                return ResourceManager.GetString("PeerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "Ping 全部".
        /// </summary>
        public static string PeerPingAll {
            get {
                return ResourceManager.GetString("PeerPingAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "显示 NAT / 延迟 / 路由 cost".
        /// </summary>
        public static string PeerHint {
            get {
                return ResourceManager.GetString("PeerHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "日志".
        /// </summary>
        public static string LogTitle {
            get {
                return ResourceManager.GetString("LogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "📋 运行日志".
        /// </summary>
        public static string LogHeader {
            get {
                return ResourceManager.GetString("LogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "清空".
        /// </summary>
        public static string LogClear {
            get {
                return ResourceManager.GetString("LogClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "复制".
        /// </summary>
        public static string LogCopy {
            get {
                return ResourceManager.GetString("LogCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "关闭".
        /// </summary>
        public static string LogClose {
            get {
                return ResourceManager.GetString("LogClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "已复制房间号".
        /// </summary>
        public static string MsgCopiedRoomId {
            get {
                return ResourceManager.GetString("MsgCopiedRoomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "已复制联机链接".
        /// </summary>
        public static string MsgCopiedLinkCode {
            get {
                return ResourceManager.GetString("MsgCopiedLinkCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "启动失败: {0}".
        /// </summary>
        public static string MsgStartupFailed {
            get {
                return ResourceManager.GetString("MsgStartupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "LinkRoom 崩溃报告".
        /// </summary>
        public static string MsgCrashTitle {
            get {
                return ResourceManager.GetString("MsgCrashTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "LinkRoom 发生了未处理的异常，已自动导出诊断包：  {0}  提交 GitHub Issue 时可附上此诊断包（含日志、脱敏设置、系统信息）。  ".
        /// </summary>
        public static string MsgCrashHeader {
            get {
                return ResourceManager.GetString("MsgCrashHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "是 = 一键创建 GitHub Issue（gh） 否 = 复制 Issue 正文 取消 = 关闭".
        /// </summary>
        public static string MsgCrashOptionsGh {
            get {
                return ResourceManager.GetString("MsgCrashOptionsGh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "是 = 复制 Issue 正文到剪贴板 否 = 打开 GitHub 手动提交 取消 = 关闭".
        /// </summary>
        public static string MsgCrashOptionsNoGh {
            get {
                return ResourceManager.GetString("MsgCrashOptionsNoGh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "(诊断导出失败)".
        /// </summary>
        public static string MsgDiagExportFailed {
            get {
                return ResourceManager.GetString("MsgDiagExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "Issue 正文已复制到剪贴板，请到 GitHub 新建 Issue 并粘贴。".
        /// </summary>
        public static string MsgIssueBodyCopied {
            get {
                return ResourceManager.GetString("MsgIssueBodyCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "Issue 已创建： {0}  链接已复制到剪贴板。".
        /// </summary>
        public static string MsgIssueCreated {
            get {
                return ResourceManager.GetString("MsgIssueCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "gh 创建 Issue 失败：{0}  Issue 正文已复制到剪贴板，请手动提交。".
        /// </summary>
        public static string MsgGhIssueFailed {
            get {
                return ResourceManager.GetString("MsgGhIssueFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "EasyTier 运行时解压失败: {0}".
        /// </summary>
        public static string MsgRuntimeExtractFailed {
            get {
                return ResourceManager.GetString("MsgRuntimeExtractFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "发现新版本 {0} 当前: v{1} 大小: {2:F1} MB".
        /// </summary>
        public static string MsgUpdateFoundTemplate {
            get {
                return ResourceManager.GetString("MsgUpdateFoundTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "  ✓ 可增量更新（保留 EasyTier 运行时）".
        /// </summary>
        public static string MsgUpdateIncremental {
            get {
                return ResourceManager.GetString("MsgUpdateIncremental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "  是=立即更新 | 否=跳过此版本 | 取消=稍后".
        /// </summary>
        public static string MsgUpdateOptions {
            get {
                return ResourceManager.GetString("MsgUpdateOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "LinkRoom 更新".
        /// </summary>
        public static string MsgUpdateTitle {
            get {
                return ResourceManager.GetString("MsgUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to "更新失败: {0}".
        /// </summary>
        public static string MsgUpdateFailed {
            get {
                return ResourceManager.GetString("MsgUpdateFailed", resourceCulture);
            }
        }
    }
}
